### ISSUE TITLE
Gravatar XML-RPC authentication

### ISSUE THREAD

**Issue by JonBunator** [pabluk/libgravatar#7]
I tried the sample code in the docs with my credentials:
```python
from libgravatar import GravatarXMLRPC
g = GravatarXMLRPC('user@domain', apikey='1234')
g.test() # test the API
```
But unfortunally I always get a bad authentication error: `Server error: Invalid Email, or Hash, or Access Denied (error code: -9)`
The apikey is available at https://apikey.wordpress.com/ right?
If anyone has any idea what the problem could be I would really appreciate it :)

**Comment by pabluk** [comment]
Hi @JonBunator,

I've just gave a try to this, that page https://apikey.wordpress.com/ gives you the good API key, but it also shows the `username` and you need instead to pass to the function the email address associated to your account.

This was my test (I replaced my API key and user info):
```python
from libgravatar import GravatarXMLRPC
g = GravatarXMLRPC('username', apikey='1234') # as showed at https://apikey.wordpress.com/
g.test()
Server error: Invalid Email, or Hash, or Access Denied (error code: -9)
```
and using the API key and an email address:
```python
from libgravatar import GravatarXMLRPC
g = GravatarXMLRPC('user@example.com', apikey='1234') # my email address and
                                                      # only the API key from https://apikey.wordpress.com/
g.test()
{'response': 1617224812}
```

Let me know if that fix your issue in order to update the documentation, and thanks for reporting it.

**Comment by JonBunator** [comment]
Thanks for the quick response! I have already used the associated email. Still not working :/ But thank you for trying it out. It has to be some issue with my account then.

**Comment by pabluk** [comment]
No problem @JonBunator, I'll update the documentation to clarify that point and the information provided at https://apikey.wordpress.com/. Thank you for your help.

**Comment by roke-julian-lockhart** [comment]
@JonBunator, if I pass the credentials as strings, it authenticates, but not if I pass them via variables. Perhaps that's your issue too?

**Comment by JonBunator** [comment]
@rokejulianlockhart I don't know, since I don't need it anymore. But thanks for the response
